random_seed: 8981
device:
  type: cuda
  ordinal: 0
dataset_dir: './bert_dataset/'
data_loader:
  max_sent_len: 128
  batch_size: 32
  n_workers: 4
net:
  bert_pretrain: 'bert-base-uncased'
  num_labels: 5
optim:
  kwargs:
    lr: 3.0e-6
    warmup: 0.1
train:
  n_epochs: 15
  max_grad_norm: 1
  n_gradient_accumulation_steps: 1  # Must be a divider of data_loader.batch_size.
models: 
    model1:
        path: './models/ensemble/ckpts/random-3319_epoch-6.ckpt'
        seed: 3319
    model2:
        path: './models/ensemble/ckpts/random-651_epoch-5.ckpt'
        seed: 651
    model3:
        path: './models/ensemble/ckpts/random-8981_epoch-9.ckpt'
        seed: 8981

